### 1. How likely is it that you roll doubles when rolling two dice?

In [1]:
import numpy as np
np.random.seed(200)

In [270]:
# 1. How likely is it that you roll doubles when rolling two dice?

n_simulations = 100_000
n_trials=2
# simulate with randint, but you could also use radmon.choice with outcomes=[1,2,3,4,5,6]
dice_rolls = np.random.randint(1, 7, size=(n_simulations, n_trials))

# Create a boolean mask. Use a slice to select column 1, and column 2 separately. If they match, True.
p_doubles = (dice_rolls[:, 0] == dice_rolls[:, 1]).mean()


print(dice_rolls)
p_doubles

[[2 2]
 [4 5]
 [1 5]
 ...
 [5 6]
 [1 1]
 [6 5]]


0.16651

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [151]:
# the 8 coins being flipped at the same time is 1 trial
n_simulations = 100_000
n_trials=8

outcomes=['H','T']

eight_flips = np.random.choice(outcomes, size=(n_simulations, n_trials))

eight_flips.shape


(100000, 8)

In [150]:
# Probability of 3 heads?

# Create boolean mask across axis 1 (column wise), if the row adds up to exactly 3, we have 3 heads.
three_heads = ((coin_flip == 'H').sum(axis=1) == 3).mean()

three_heads

0.2174

In [145]:
# Probability of more than 3 heads?

# If the row adds up to more than 3, we have more than 3 Trues with our boolean mask.
more_than_three = ((coin_flip == 'H').sum(axis=1) > 3).mean()

more_than_three

0.6379

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [170]:
n_simulations = 100_000
n_trials=2
# simulate with random.choice and enter outcomes directly
alumni = np.random.choice(['web', 'web', 'web', 'data'], size= (n_simulations,n_trials))
print(alumni)
# boolean mask for 'data'
# sum mask across axis 1, if sum = 2, then we got two data alumi in a trail.
both_data = ((alumni == 'data').sum(axis=1) == 2).mean()
both_data



# note: this can be broken down into more variables so it's easier to follow.
#       boolean mask can be one variable, sum across axis 1 can be another variable, and so on.
#       It may be confusing if you have a lot of code on one line

[['web' 'data']
 ['web' 'web']
 ['data' 'web']
 ...
 ['data' 'data']
 ['web' 'web']
 ['web' 'web']]


0.06197

In [173]:
# another way, use probability within the np.random.choice
n_simulations = 100_000
n_trials=2
alumni = np.random.choice(['web', 'data'], size=(n_simulations, n_trials), p=(0.75, 0.25))

# the number of times both billboards have data science students on them without using .mean()
n_data = np.sum((alumni == 'data').all(axis=1))

p_data = n_data / n_simulations
p_data

0.06302

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [204]:
n_simulations = 100_000

μ =3
σ = 1.5
week = 5
# simulate with normal since we have mean and std
packages_sold = np.random.normal(μ, σ, (n_simulations, week))
# print(packages_sold)
total_purchased=np.sum(packages_sold, axis=1)
# print(total_purchased)
# less than 16 means there is at least 1 tart left I can buy
tart_on_friday=np.mean(total_purchased <=16)
tart_on_friday



0.61784

### 5. Compare Heights

 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - Since you have means and standard deviations, you can use np.random.normal to generate observations.
 - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [4]:
# Create your variables
n_simulations = 100_000
m_mean, m_std = 178, 8
f_mean, f_std = 170, 6

# Generate two separate simulation arrays
male_heights = np.random.normal(m_mean, m_std, (n_simulations, 1))
female_heights = np.random.normal(f_mean, f_std, (n_simulations, 1))

male_heights


array([[172.03999495],
       [173.23335034],
       [185.89438636],
       ...,
       [166.49035566],
       [184.0312187 ],
       [195.83793715]])

In [5]:
female_heights


array([[170.28446828],
       [166.81632638],
       [164.77993823],
       ...,
       [157.75328529],
       [172.77270859],
       [176.70931508]])

In [229]:
# in one line of code: create mask and find the average with np.mean
p_taller_woman = np.mean(female_heights > male_heights)
p_taller_woman


0.2128

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

 - What is the probability that we observe an installation issue within the first 150 students that download anaconda?

 - How likely is it that 450 students all download anaconda without an issue?

In [266]:
# probability 50 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 50 
install_simulations = np.random.random((n_simulations, n_trials))
# no install fails means our trials must fall under the 1/250 chance
no_fails_50 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_50

0.82015

In [241]:
# probability 100 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 100 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_100 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_100

0.67162

In [6]:
# probability 150 students: AT LEAST ONE install fail
n_simulations = 100_000
install_fails = 1/250
n_trials = 150 
install_simulations = np.random.random((n_simulations, n_trials))
# greater than one checks for trials that have at least one fail
no_fails_150 = ((install_simulations < install_fails).sum(axis=1) > 0).mean()

no_fails_150


0.45236

In [268]:
# probability 450 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 450 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_450 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_450

0.16498

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

 - How likely is it that a food truck will show up sometime this week?

In [7]:
# three days with NO truck
n_simulations = 100_000
n_trials = 3 
# simulate with choice, enter outcomes directly, add probabilty to put more weight on a truck showing up
truck_simulations = np.random.choice(['truck', 'no_truck'], size=(n_simulations, n_trials), p=(0.7, 0.3))

# boolean mask when a truck shows up and if they do not show up in a trial the sum will equal to 0
odds_of_no_truck= ((truck_simulations == 'truck').sum(axis=1) == 0).mean()

odds_of_no_truck

0.02721

In [299]:
# four days remaining in the week
# odds that a truck is there
n_simulations = 100_000
n_trials = 4 

truck_simulations = np.random.choice(['truck', 'no_truck'], size=(n_simulations, n_trials), p=(0.7, 0.3))
# boolean mask for any truck in 4 days
odds_of_truck= ((truck_simulations == 'truck').sum(axis=1) > 0).mean()
truck_simulations
odds_of_truck

0.99192

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [2]:
import pandas as pd
n_simulations=100_000
n_trials=23
# simulate with randint for 365 days, trails are number of people in room
bday_simulation= np.random.randint(1,366, size=(n_simulations,n_trials))

bday_simulation

array([[283, 106, 273, ..., 144, 130, 239],
       [280,  86, 264, ..., 162, 201, 129],
       [181, 347, 190, ...,  98, 152, 169],
       ...,
       [364, 200, 175, ..., 278, 241, 188],
       [276,  33,  29, ..., 144, 309,  20],
       [335, 320, 251, ..., 240, 141, 356]])

In [21]:
# create dataframe
df = pd.DataFrame(bday_simulation)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  16  \
0  283  106  273  325  299  184  333   80  346   15  ...  140   43  313   2   
1  280   86  264  311  273  363  292  245  160  188  ...  243  129  132  56   
2  181  347  190  327  100   77  187  325  191   53  ...  193  346  179  98   
3  283  194  354   82  328  219    1  174   83   39  ...  235  144  338  30   
4  249  229  244   30  231  111  161  192   44  127  ...  213  365  150  46   

    17   18   19   20   21   22  
0    8   52  202  144  130  239  
1  352  185    4  162  201  129  
2  217  136  186   98  152  169  
3  114  201  244  193   28  200  
4  184  307  225   62  299  138  

[5 rows x 23 columns]

In [4]:
# use nunique (only works with DataFrames) counts number of distinct elements in specified axis
df.nunique(axis=1)

0        23
1        21
2        22
3        23
4        23
         ..
99995    22
99996    23
99997    21
99998    23
99999    22
Length: 100000, dtype: int64

In [7]:
# average of the boolean mask where true if nunique falls bellow 23 (meaning we have at least one matching birthday in a trial)
(df.nunique(axis=1) < 23).mean()

0.50784

In [11]:
# 20 people 

n_simulations=100_000
n_trials=20

bday_simulation_20= np.random.randint(1,366, size=(n_simulations,n_trials))
bday_simulation_20


array([[117, 330, 100, ...,  21, 203,  85],
       [161, 273, 353, ..., 252, 151, 105],
       [205, 350, 286, ..., 275,  58,  92],
       ...,
       [242,  38, 153, ..., 272, 357, 330],
       [207, 355,  86, ...,  69, 326, 111],
       [154, 101, 117, ...,  46, 322,  88]])

In [20]:
# change to dataframe
df2 = pd.DataFrame(bday_simulation_20)
df2.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  117  330  100  221  241  217  223  346  344  352   18  145   55  101  148   
1  161  273  353  256  110  315   81  236  210  200  339  330  261  108   63   
2  205  350  286   56  185  223  135  336  351   98  110  114  116  342  284   
3  297  122  215  184  249  214   41  186  318   38  364   87  138    3  351   
4  178   12  148   54  198  224   17  323  293  273  263  236  291   17  359   

    15   16   17   18   19  
0  157   63   21  203   85  
1  262  260  252  151  105  
2   24   40  275   58   92  
3   58  253  274  120  108  
4   54  219  229  174   21

In [13]:
# use nunique
df2.nunique(axis=1)

0        20
1        20
2        20
3        20
4        18
         ..
99995    20
99996    19
99997    19
99998    19
99999    19
Length: 100000, dtype: int64

In [16]:
# average of the boolean mask where true if nunique falls bellow 20 (meaning we have at least one matching birthday in a trial)
(df2.nunique(axis=1) < 20).mean()

0.41179

In [22]:
# 40 people 

n_simulations=100_000
n_trials=40

bday_simulation_40= np.random.randint(1,366, size=(n_simulations,n_trials))
bday_simulation_40


array([[194,   1, 243, ...,  54, 120,  68],
       [314, 296, 143, ...,  10,  24, 314],
       [113, 143,  65, ...,  25, 128,   7],
       ...,
       [ 92, 292, 355, ...,  27, 192, 286],
       [ 70, 230, 322, ..., 149, 104, 208],
       [137,  37, 342, ..., 166,  77, 272]])

In [25]:
# change to dataframe

df40 = pd.DataFrame(bday_simulation_40)
df40.head()

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0  194    1  243  157   22  136  209  329  322    5  ...  247   80  136   14   
1  314  296  143  258  112   51  162  140  319  336  ...    9  306  167  168   
2  113  143   65  251  119  215   82  255  271  110  ...  185  249  228    1   
3   94   45  105  136  136  179  255   13  117  323  ...  239  200  237    1   
4   38   88   54  302  314   85   84  319  330  186  ...   79  145   89   95   

    34   35   36   37   38   39  
0   43  318   40   54  120   68  
1  168  223   52   10   24  314  
2  272    9   70   25  128    7  
3  352  175  245  206  281   44  
4   51  235   11  190  349  232  

[5 rows x 40 columns]

In [24]:
# use nunique

df40.nunique(axis=1)

0        38
1        36
2        38
3        39
4        39
         ..
99995    39
99996    39
99997    37
99998    38
99999    37
Length: 100000, dtype: int64

In [29]:
# average of the boolean mask where true if nunique falls bellow 40 (meaning we have at least one matching birthday in a trial)
(df40.nunique(axis=1) < 40).mean()

0.89224