### 1. How likely is it that you roll doubles when rolling two dice?

In [120]:
import numpy as np
np.random.seed(200)

In [270]:
# 1. How likely is it that you roll doubles when rolling two dice?

n_simulations = 100_000
n_trials=2

dice_rolls = np.random.randint(1, 7, size=(n_simulations, n_trials))

# Create a boolean mask. Use a slice to select column 1, and column 2 separately. If they match, True.
p_doubles = (dice_rolls[:, 0] == dice_rolls[:, 1]).mean()


print(dice_rolls)
p_doubles

[[2 2]
 [4 5]
 [1 5]
 ...
 [5 6]
 [1 1]
 [6 5]]


0.16651

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [151]:
n_simulations = 100_000
n_trials=8

outcomes=['H','T']

eight_flips = np.random.choice(outcomes, size=(n_simulations, n_trials))

eight_flips.shape


(100000, 8)

In [150]:
# Probability of 3 heads?

# If the row adds up to 3 exactly 3, we have 3 heads.
three_heads = ((coin_flip == 'H').sum(axis=1) == 3).mean()

three_heads

0.2174

In [145]:
# Probability of more than 3 heads?

# If the row adds up to more than 3, we have more than 3 Trues with our boolean mask.
more_than_three = ((coin_flip == 'H').sum(axis=1) > 3).mean()

more_than_three

0.6379

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [170]:
n_simulations = 100_000
n_trials=2
alumni = np.random.choice(['web', 'web', 'web', 'data'], size= (n_simulations,n_trials))
print(alumni)
# boolean mask for data
# sum mask across axis 1, if sum = 2, then we got two data alumi in a trail.
both_data = ((alumni == 'data').sum(axis=1) == 2).mean()
both_data


[['web' 'data']
 ['web' 'web']
 ['data' 'web']
 ...
 ['data' 'data']
 ['web' 'web']
 ['web' 'web']]


0.06197

In [173]:
# another way, use probability within the np.random.choice
n_simulations = 100_000
n_trials=2
alumni = np.random.choice(['web', 'data'], size=(n_simulations, n_trials), p=(0.75, 0.25))

# the number of times both billboards have data science students on them without .mean
n_data = np.sum((alumni == 'data').all(axis=1))

p_data = n_data / n_simulations
p_data

0.06302

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [204]:
n_simulations = 100_000

μ =3
σ = 1.5
week = 5

packages_sold = np.random.normal(μ, σ, (n_simulations, week))
# print(packages_sold)
total_purchased=np.sum(packages_sold, axis=1)
# print(total_purchased)
tart_on_friday=np.mean(total_purchased <=16)
tart_on_friday



0.61784

### 5. Compare Heights

 - Men have an average height of 178 cm and standard deviation of 8cm.
 - Women have a mean of 170, sd = 6cm.
 - Since you have means and standard deviations, you can use np.random.normal to generate observations.
 - If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [222]:
# Initialize variables
n_simulations = 100_000
m_mean, m_std = 178, 8
f_mean, f_std = 170, 6

# Generate the two separate columns
male_heights = np.random.normal(m_mean, m_std, (n_simulations, 1))
female_heights = np.random.normal(f_mean, f_std, (n_simulations, 1))

print(male_heights)


[[179.39131815]
 [191.04683495]
 [180.16787609]
 ...
 [177.49250797]
 [182.2242564 ]
 [166.07776054]]


In [223]:
print(female_heights)


[[178.57677929]
 [170.43890686]
 [172.63532944]
 ...
 [174.84038018]
 [164.21215042]
 [169.96019047]]


In [229]:
p_taller_woman = np.mean(female_heights > male_heights)
p_taller_woman


0.2128

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

 - What is the probability that we observe an installation issue within the first 150 students that download anaconda?

 - How likely is it that 450 students all download anaconda without an issue?

In [266]:
# probability 50 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 50 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_50 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_50

0.82015

In [241]:
# probability 100 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 100 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_100 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_100

0.67162

In [269]:
# probability 150 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 150 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_150 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_150


0.54791

In [268]:
# probability 450 students: NO install fails
n_simulations = 100_000
install_fails = 1/250
n_trials = 450 
install_simulations = np.random.random((n_simulations, n_trials))

no_fails_450 = ((install_simulations < install_fails).sum(axis=1) == 0).mean()

no_fails_450

0.16498

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

 - How likely is it that a food truck will show up sometime this week?

In [294]:
# three days with no truck
n_simulations = 100_000
n_trials = 3 

truck_simulations = np.random.choice(['truck', 'no_truck'], size=(n_simulations, n_trials), p=(0.7, 0.3))

odds_of_no_truck= ((truck_simulations == 'truck').sum(axis=1) == 0).mean()
truck_simulations
odds_of_no_truck

0.0273

In [299]:
# four days remaining in the week
# odds that a truck is there
n_simulations = 100_000
n_trials = 4 

truck_simulations = np.random.choice(['truck', 'no_truck'], size=(n_simulations, n_trials), p=(0.7, 0.3))
# boolean mask for any truck in 4 days
odds_of_truck= ((truck_simulations == 'truck').sum(axis=1) > 0).mean()
truck_simulations
odds_of_truck

0.99192

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [323]:
import pandas as pd
n_simulations=100_000
n_trials=23

bday_simulation= np.random.randint(1,366, size=(n_simulations,n_trials))
bday_simulation

array([[114, 248, 254, ..., 186,  38, 230],
       [354, 147, 200, ...,  54, 119, 239],
       [179,  68, 298, ..., 215, 181, 103],
       ...,
       [113, 312,  95, ...,   1, 311, 147],
       [133, 106, 364, ...,  85, 120, 266],
       [250, 185, 316, ...,   9, 337, 327]])

In [324]:
df = pd.DataFrame(bday_simulation)
df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      114  248  254   36  242  133  118   88  181  313  ...  256  180  344   
1      354  147  200  210   40  127   66  184   46   33  ...   83  282  218   
2      179   68  298  263   22  294  154  363  307   72  ...  289   10  249   
3      337  355  358  116  154  147  183  275   89  363  ...  224   37   17   
4      110  230  277  248  175  351  293  320  135  332  ...   16  225  350   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  252  336  248  299  299   62  138  269  353  190  ...  191  172  153   
99996  217   85  230  115  135  180  313  268   83   55  ...   96  203  283   
99997  113  312   95  280    8  214  301   96  216  320  ...   95   10  178   
99998  133  106  364   66  247  160  211  124  133   46  ...  125   92   39   
99999  250  185  316  258   46  102   62  309  159  293  ...  277  218  134   

        16   17   18   19   20   21   22  
0      331    8  282  259  186   38  230  
1      105    5  196  185   54  119  239  
2      145  256  237  290  215  181  103  
3      255   56  117  238  272   31  295  
4       71  269   74  177  168  234  224  
...    ...  ...  ...  ...  ...  ...  ...  
99995   36  127   68  297   45  241   34  
99996   91    1  284   29   24  137   72  
99997    4   32  119  247    1  311  147  
99998   11  169  220   76   85  120  266  
99999    5  264  228  178    9  337  327  

[100000 rows x 23 columns]

In [325]:
df.nunique(axis=1)

0        23
1        23
2        23
3        23
4        23
         ..
99995    22
99996    22
99997    22
99998    21
99999    23
Length: 100000, dtype: int64

In [326]:
mask= df.nunique(axis=1)!=23
mask

0        False
1        False
2        False
3        False
4        False
         ...  
99995     True
99996     True
99997     True
99998     True
99999    False
Length: 100000, dtype: bool

In [327]:
mask.mean()

0.50619

In [341]:
# 20 people 

n_simulations=100_000
n_trials=20

bday_simulation_20= np.random.randint(1,366, size=(n_simulations,n_trials))
bday_simulation_20


array([[295, 257, 164, ...,  79, 222, 256],
       [287, 224,  84, ..., 328, 283,  27],
       [344, 153,  27, ..., 242,  28,  77],
       ...,
       [301,  14, 109, ..., 355, 141, 359],
       [202, 301,  81, ...,  92, 160,  75],
       [ 29, 217, 266, ..., 173, 195, 347]])

In [342]:
df2 = pd.DataFrame(bday_simulation_20)
df2

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0      295  257  164  160   10  203  213   86  271    7  334  204   73   33   
1      287  224   84   70  328  263  265  130   21  158  294  144  312  288   
2      344  153   27   60  350  148  118  233  186  136  175  279   93  304   
3      193  228   76  156   64  243  323  280   44  339   62  236  296   65   
4      286  163  244   37  276  280  310    3   95  174  305  146  280  292   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  339  277  151  269   95  214  258  216  137  183  276  290   73  328   
99996  318   10  175  292   63  111  283   75   67  318  318  224  338  156   
99997  301   14  109  151  208  149  134    4   53  110   89  316  269  353   
99998  202  301   81  281  140  360   88  104  301  227   11   17  274  247   
99999   29  217  266  193  244  125  203  223  345  156   31  334  170   88   

        14   15   16   17   18   19  
0      109  117  332   79  222  256  
1       48  169  201  328  283   27  
2      355  219  164  242   28   77  
3      316  278  111  136  270  127  
4       66  193  174  182   94  167  
...    ...  ...  ...  ...  ...  ...  
99995  247  134   98  226  119  244  
99996  237  349   25  355    3  177  
99997  114  164  322  355  141  359  
99998  312  214  140   92  160   75  
99999  354  112  185  173  195  347  

[100000 rows x 20 columns]

In [343]:
df2.nunique(axis=1)

0        20
1        19
2        20
3        20
4        18
         ..
99995    20
99996    18
99997    20
99998    18
99999    20
Length: 100000, dtype: int64

In [344]:
mask2= df2.nunique(axis=1)!=20
mask2

0        False
1         True
2        False
3        False
4         True
         ...  
99995    False
99996     True
99997    False
99998     True
99999    False
Length: 100000, dtype: bool

In [345]:
mask2.mean()

0.41577

In [351]:
# 40 people 

n_simulations=100_000
n_trials=40

bday_simulation_40= np.random.randint(1,366, size=(n_simulations,n_trials))
bday_simulation_40


array([[101, 147, 332, ..., 236,  16,  25],
       [ 63, 180, 192, ..., 298,  12, 350],
       [310,  38, 108, ...,  83, 195, 110],
       ...,
       [ 60, 197,  43, ..., 198,  37, 154],
       [208,  84, 323, ..., 187, 190, 270],
       [ 67, 151, 190, ..., 291, 180, 311]])

In [352]:
df40 = pd.DataFrame(bday_simulation_40)
df40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0      101  147  332  188   54  221  262  105  249   24  ...  322  269  293   
1       63  180  192  260  264  252  225   18  240  291  ...   23   67  272   
2      310   38  108  146  290  332   35  307  296   40  ...  126   39   17   
3      100  128  105  113  282   14  189   91  177   93  ...  278  198  138   
4      340  111  301  175  307   86  247  336    3  236  ...  186  299   56   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  175  343  220   13  107  318  228  294  183  167  ...   25   83  293   
99996  133  214  345  273  101  260   80   73  166   38  ...  272  334  301   
99997   60  197   43  354  220  181  137  143   12  342  ...  253   95    5   
99998  208   84  323  337   66  154   79  105  100  237  ...   35   58  215   
99999   67  151  190   30  327  231  176  276  312   15  ...  190  226  280   

        33   34   35   36   37   38   39  
0      168  219  259  265  236   16   25  
1      245   30  227  232  298   12  350  
2       26   11   10  236   83  195  110  
3      256  349  168   24  348  179   49  
4      355  155  142  168  160  102  205  
...    ...  ...  ...  ...  ...  ...  ...  
99995  193  199  196   46  157   33  273  
99996  140  198  189   85  291  118    3  
99997  247  184  235  103  198   37  154  
99998  238   70  257  256  187  190  270  
99999  356  195   62  200  291  180  311  

[100000 rows x 40 columns]

In [353]:
df40.nunique(axis=1)

0        39
1        39
2        38
3        38
4        38
         ..
99995    36
99996    38
99997    37
99998    35
99999    38
Length: 100000, dtype: int64

In [354]:
mask40= df40.nunique(axis=1)!=40
mask40

0        True
1        True
2        True
3        True
4        True
         ... 
99995    True
99996    True
99997    True
99998    True
99999    True
Length: 100000, dtype: bool

In [355]:
mask40.mean()

0.89233